### ISSUE TITLE
Cannot compile with gcc/13.2.1 or clang/17.0.6 error: inlining failed in call to always_inline _mm_crc32_u32: target specific option mismatch

### ISSUE THREAD

**Issue by gcflymoto** [dougallj/zlib-dougallj#6]
gcc/13.2.1
```
/opt/rh/gcc-toolset-13/root/usr/lib/gcc/x86_64-redhat-linux/13/include/smmintrin.h:834:1: error: inlining failed in call to ?always_inline? ?_mm_crc32_u32?: target specific option mismatch
  834 | _mm_crc32_u32 (unsigned int __C, unsigned int __V)
      | ^~~~~~~~~~~~~
deflate.c:150:12: note: called from here
  150 |     return _mm_crc32_u32(0, *(uint32_t*)str) & s->hash_mask;
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
clang/17
```
deflate.c:150:12: error: always_inline function '_mm_crc32_u32' requires target feature 'crc32', but would be inlined into function 'hash_func' that is compiled without support for 'crc32'
  150 |     return _mm_crc32_u32(0, *(uint32_t*)str) & s->hash_mask;
```
